---
description: "Software engineer"
timezone: America/Puerto_Rico
markdown: kramdown
highligther: rouge
title: George Pérez Marrero
author: George Pérez Marrero
url: https://georgeperez.dev
email: george@perezmarrero.com
repository: georgeperez/georgeperez.dev
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
  - static.json
  - photos.html
sass:
  sass_dir: _scss
  style: compressed
